name: CI_CD PETHUG_API

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Github Container Registy
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/karnkm/pethug-project-dev:latest

      - name: Push Docker image to Github Container registry
        run: |
          docker push ghcr.io/karnkm/pethug-project-dev:latest
