name: CI_CD PETHUG_API

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Github Container Registy
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/karnkm/pethug-project-api-dev:latest

      - name: Push Docker image to Github Container registry
        run: docker push ghcr.io/karnkm/pethug-project-api-dev:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login ssh to remote server and deploy container
        uses: appleboy/ssh-action@master
        env:
          MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME  }}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD  }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: MONGO_ROOT_USERNAME,MONGO_ROOT_PASSWORD
          script: |
            export MONGO_ROOT_USERNAME=$MONGO_ROOT_USERNAME
            export MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
            docker ps -a
            docker-compose stop api
            docker pull ghcr.io/karnkm/pethug-project-api-dev:latest
            docker images
            docker-compose up -d api
            docker image prune -f
            docker ps -a
